---
#- name: Ensure flow-tools is installed
#  apt: name=flow-tools state=present
- name: Ensure every workdir for every router is exiting
  file: path={{item.workdir}} state=directory
  with_items: flowtools.captures

- name: Setting flow-capture
  template: src=flow-capture.j2 dest=/etc/flow-tools/flow-capture.conf
  notify:
    - Restart flow-capture
